### ISSUE TITLE
Constant Crashes in 119.0.6045.214

### ISSUE THREAD

**Issue by creeperlv** [Alex313031/Thorium-WOA#2]
**System Details**
 - OS: Windows 11 Pro 22631.2861 Arm64
 - Thorium Version M119.0.6045.214

**Problem**
All page crashes including NTP, and settings page.

**Screenshots**
![image](https://github.com/Alex313031/Thorium-WOA/assets/7870727/26994fe7-1fe2-499e-ac04-5d6a0fc2d640)
![image](https://github.com/Alex313031/Thorium-WOA/assets/7870727/b5a8b5c8-6a10-41dc-bb97-66d09de27f0b)

**Additional Notes**
Memory Dump in User Data/Crashpad/reports:
[cdd9698e-66d4-445a-a475-dc1661b36fdd.dmp](https://github.com/Alex313031/Thorium-WOA/files/13852588/cdd9698e-66d4-445a-a475-dc1661b36fdd.dmp)

**Comment by Alex313031** [comment]
@creeperlv YUP. I wasn't able to test until after I released it. See the new release notes > https://github.com/Alex313031/Thorium-WOA/releases/tag/M119.0.6045.214
