### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by RossBogdanov** [Alex313031/Thorium-WOA#4]
Since the latest version M121.0.6167.204 - 5th Release for Windows on ARM (arm64) systems is available as of 21.05.2024, please update it to the most recent version M124.x.xxxx.xxx

Thank you in advance.

**Comment by gz83** [comment]
The new version is being compiled, but it is not guaranteed to be released. This is because many compilation errors are often encountered when compiling the WOA version.

**Comment by RossBogdanov** [comment]
I understand, hope that everything will get better and the release will take place soon. Thank you.

**Comment by gz83** [comment]
The new WOA version has been compiled and is currently waiting for Alex to conduct the final testing and release process.

@RossBogdanov

**Comment by Alex313031** [comment]
@RossBogdanov Here you go sir > https://github.com/Alex313031/Thorium-WOA/releases/tag/M124.0.6367.218

**Comment by RossBogdanov** [comment]
thank you so much
