### ISSUE TITLE
s something wrong with my sidebar? It keeps showing red.

### ISSUE THREAD

**Issue by FEI352** [Alex313031/Thorium-WOA#5]
**System Details**
 - OS: [windows11]
 - Thorium Version [M124.0.6367.218  b9b0490 M124.0.6367.218 - 6th Release]

**Problem**

**Screenshots**
![image](https://github.com/Alex313031/Thorium-WOA/assets/104716040/b156b9d4-c7d8-439c-bf24-0097e13cac49)

**Comment by FEI352** [comment]
This bug only appears in the latest version; it didn't occur in the previous version. However, the previous version doesn't support multiple users.

**Comment by Alex313031** [comment]
@FEI352 Fixed in latest M126 version.
